export enum SettingsFormControls {
    apiToken = 'apiToken',
    apiUrl = 'apiUrl',
    paymentPeriod = 'paymentPeriod',
    sellerName = 'sellerName',
    sellerStreet = 'sellerStreet',
    sellerPostCode = 'sellerPostCode',
    sellerCity = 'sellerCity',
    sellerCountry = 'sellerCountry',
    sellerTaxNumber = 'sellerTaxNumber',
    sellerBank = 'sellerBank',
    sellerBankAccountPln = 'sellerBankAccountPln',
    sellerBankAccountEur = 'sellerBankAccountEur',
    exchangeCurrency = 'exchangeCurrency',
    currency = 'currency',
    description = 'description',
    quantity = 'quantity',
    quantityUnit = 'quantityUnit',
    tax = 'tax',
}